<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.fiap</groupId>
    <artifactId>hospital-system</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>hospital-system</name>
    <description>Agregador dos serviços do Hospital System - Tech Challenge FIAP Fase 3</description>

    <modules>
        <module>api-agendamento</module>
        <module>api-notificacao</module>
    </modules>

</project>