spring.application.name=api-agendamento
server.port=8081

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/hospital_db}
spring.datasource.username=${POSTGRES_USER:hospital}
spring.datasource.password=${POSTGRES_PASSWORD:hospital}
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:hospital}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:hospital}

spring.jpa.hibernate.ddl-auto=none

spring.flyway.schemas=agendamento
spring.flyway.default-schema=agendamento