spring.application.name=api-agendamento
server.port=8081

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/hospital_db}
spring.datasource.username=${POSTGRES_USER:hospital}
spring.datasource.password=${POSTGRES_PASSWORD:hospital}
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:hospital}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:hospital}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=agendamento

spring.flyway.schemas=agendamento
spring.flyway.default-schema=agendamento

agendamento.lembrete.intervalo-ms=${AGENDAMENTO_LEMBRETE_INTERVALO_MS:3600000}
