type Query {
    usuarioAutenticado: UsuarioAutenticado!
    agendamentos: [Agendamento!]!
    agendamentosPorPaciente(idPaciente: ID!): [Agendamento!]!
}

type Mutation {
    registrarConsulta(
        pacienteId: ID!
        medicoId: ID!
        dataHora: String!
        especialidade: String!
        observacoes: String
    ): Agendamento!

    editarConsulta(
        idConsulta: ID!
        dataHora: String
        status: StatusAgendamento
        especialidade: String
        observacoes: String
    ): Agendamento!
}

type UsuarioAutenticado {
    id: ID!
    nome: String!
    email: String!
    tipo: TipoUsuario!
    authorities: [String!]!
}

type Agendamento {
    id: ID!
    medicoId: ID!
    pacienteId: ID!
    dataHora: String!
    status: StatusAgendamento!
    especialidade: String!
    observacoes: String
    createdAt: String!
    updatedAt: String!
}

enum StatusAgendamento {
    AGENDADA
    CANCELADA
    REALIZADA
    REMARCADA
}

enum TipoUsuario {
    MEDICO
    ENFERMEIRO
    PACIENTE
}
