scalar DateTime

type Query {
    usuarioAutenticado: UsuarioAutenticado!
    agendamentosPorPaciente(idPaciente: ID!): [Agendamento!]!
    historicoConsultas(filter: HistoricoConsultaFiltro): [HistoricoConsulta!]!
}

type Mutation {
    registrarConsulta(input: RegistrarConsultaInput!): Agendamento!
    editarConsulta(
        idConsulta: ID!
        input: EditarConsultaInput
    ): Agendamento!
}

input RegistrarConsultaInput {
    pacienteId: ID!
    medicoId: ID!
    dataHora: DateTime!
    especialidade: String!
    observacoes: String
}

input EditarConsultaInput {
    dataHora: DateTime
    status: StatusAgendamento
    especialidade: String
    observacoes: String
}

type UsuarioAutenticado {
    id: ID!
    nome: String!
    email: String!
    tipo: TipoUsuario!
    authorities: [String!]!
}

type Agendamento {
    id: ID!
    medicoId: ID!
    pacienteId: ID!
    dataHora: DateTime!
    status: StatusAgendamento!
    especialidade: String!
    observacoes: String
    createdAt: DateTime!
    updatedAt: DateTime!
}

type HistoricoConsulta {
    id: ID!
    medicoId: ID!
    pacienteId: ID!
    dataHora: DateTime!
    status: StatusAgendamento!
    especialidade: String!
    observacoes: String
    createdAt: DateTime!
    updatedAt: DateTime!
}

input HistoricoConsultaFiltro {
    status: StatusAgendamento
    apenasFuturas: Boolean
}

enum StatusAgendamento {
    AGENDADA
    CANCELADA
    REALIZADA
    REMARCADA
}

enum TipoUsuario {
    MEDICO
    ENFERMEIRO
    PACIENTE
}
